### ISSUE TITLE
Server&TPT

### ISSUE THREAD

**Issue by handicraftsman** [cracker64/tptmp#11]
Jacob, can you update starcatcher.us to new TPT version? I can't join

**Comment by jacob1** [comment]
I've updated the server to accept clients from both versions temporarily. A new version of tptmp needs to come soon to fix shift, maybe we can finish tptmp 1.0 (needs more testing)

**Comment by jacob1** [comment]
tptmp .87 is out to fix 91.0 compatibility, and i've blocked 90.2 clients now
