### ISSUE TITLE
nil - sell

### ISSUE THREAD

**Issue by handicraftsman** [cracker64/tptmp#12]
````
/home/ancient/tpt/tptmp.lua:1337: attempt to perform arithmetic on field 'sell' (a nil value)
````

**Comment by handicraftsman** [comment]
Is it easter egg?

**Comment by jacob1** [comment]
This usually happens when a new element gets added but we forgot to add support for it.

The new erase wall, I assume?

**Comment by handicraftsman** [comment]
CRMC

**Comment by handicraftsman** [comment]
Ahh, no - erase-all tool

**Comment by jacob1** [comment]
TODO: Walls just don't work at all in tpt++ either
