### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by handicraftsman** [cracker64/tptmp#13]
Command: `/snames`
Accepts no arguments. Shows nicknames of all users in all rooms (without telling room names)

**Comment by jacob1** [comment]
Unless we overhaul the room system to have public / private rooms / people, i'm not going to add this command. And if I did add those things, both would be private by default.

I don't want people spamming other people with /msg, often people will come on tptmp and immediately join some random private room, so obviously they organized a meeting outside of the game. And also, most people who join private rooms don't want to be disturbed.
