### ISSUE TITLE
Adding Copy and Paste

### ISSUE THREAD

**Issue by brianSites** [cracker64/tptmp#23]
I would appreciate it if you added the ability to copy and paste things in the TPTMP window. This is an issue because sometimes you have a long piece of text, say a link or something and you need to type it in letter by letter. And when you finish, the other person also has to type it in letter by letter. It seems like too much trouble just to share a piece of text or a link.

**Comment by jacob1** [comment]
This was already added in a pull request this morning: https://github.com/The-Powder-Toy/tptmp/pull/22

Ctrl+c to copy and ctrl+v to paste. Right clicking a line in the history will copy it (note, only copies the line, not the whole message if it got split into multiple lines)

I will release it later, I'm waiting to see how many PRs @Geniusz1 is planning on sending. Then I also want to add the username validation (server-side change)
