### ISSUE TITLE
Rename lobby to lobby instead of null

### ISSUE THREAD

**Issue by brianSites** [cracker64/tptmp#25]
I know that null in Lua and a bunch of other languages means undefined but like I can't remember how many times I tried to return to the lobby thinking the lobby's room name is "lobby". Imagine you have just installed TPT and went into a room with someone else. But the person in the room had to leave for whatever reason and now you are stuck in a random room out of the limitless possibilities (I did the calculations and the room name is one out of infinite rooms since that name can be however long and the room name does not have to obey proper spelling.). So naturally, you type in "lobby". That should bring you to the lobby, right? Wrong. Now you're in a room and no one can join to help you out. You can rename the lobby to "lobby" or at least add a /lobby command.

**Comment by LBPHacker** [comment]
Already being addressed in #24. ~~Also, no, in Lua null is `nil`.~~

**Comment by jacob1** [comment]
You're probably working with Geniusz1, but try not to duplicate issues. He's already opening pull requests for these things.
