### ISSUE TITLE
Running /connect crashes my client

### ISSUE THREAD

**Issue by Meaxis** [cracker64/tptmp#29]

**Comment by Meaxis** [comment]
Edit: It freezes for a lot of time then says "closed". It also closes on my self-hosted server.

Server Logs:
New connection: my.ip.adress.here:64534
Assigned ID is 0
0: Connection to my.ip.adress.here:64534 closed: Invalid Connect
nothing to leave

**Comment by jacob1** [comment]
This was an issue with the actual server, should be resolved now. I don't see why it would happen on a self-hosted server though. Maybe something is setup wrong there? Or the selfhosted server is missing some component needed to connect.
