### ISSUE TITLE
Can't join starcatcher.us - requires TPTMP 0.85, but i have TPTMP 0.86

### ISSUE THREAD

**Issue by handicraftsman** [cracker64/tptmp#9]

**Comment by cracker64** [comment]
The version string ".86" is not used for compatibility checks, if you can't join something else is wrong, you currently need to use 90.2 TPT with the 'stable' branch from here (latest is .86)

**Comment by handicraftsman** [comment]
Using TPT 90.2. Upgraded to git-version. When starting: TPT version not supported.

**Comment by jacob1** [comment]
Don't use the latest git version. Use this branch instead: https://github.com/cracker64/tptmp/tree/stable

tptmp 1.0 has a ton of rewrites but is unreleased at the moment.

**Comment by handicraftsman** [comment]
... Upgraded after seeing this problem...

**Comment by cracker64** [comment]
If you get the error "Tpt version not supported" you are using the wrong script.
The current server requires the "stable" branch client.lua, which is here ( https://github.com/cracker64/tptmp/raw/stable/client.lua )
Use this and delete your current client.lua.

If you have the script manager, you can download TPTMulti from that, which is the right version.

If you still get "Tpt version not supported" you have the wrong Powder.exe

**Comment by handicraftsman** [comment]
I don't have Powder.exe - i am linuxoid xD

**Comment by handicraftsman** [comment]
Loaded and see: Please update to TPTMP .85

**Comment by handicraftsman** [comment]
Renaming back to client.lua (using autorun.lua) did not helped

**Comment by jacob1** [comment]
I'm really confused by what your issue is ... can you paste the output of these commands so I know what versions of stuff you are using:

tpt.version.major, tpt.version.minor, tpt.version.build
TPTMP.version, TPTMP.versionStr
platform.platform(), platform.build(), platform.exeName()   (full exe path isn't important)

**Comment by handicraftsman** [comment]
90, 2, 322
2, 0.86
console:1: attempt to index global 'platform' (a nil value)

**Comment by jacob1** [comment]
Well that is entirely as expected. I don't see why the server would possibly reject you for that. Are you connecting to the right server? The default script should, it is /connect starcatcher.us

Maybe you can take a screenshot of the error or something.

**Comment by handicraftsman** [comment]
![screenshot from 2016-01-27 23-08-05](https://cloud.githubusercontent.com/assets/6382804/12628241/e1aa40aa-c54a-11e5-8575-26d25fefd4a3.png)

**Comment by handicraftsman** [comment]
P. S. Why your console does not shows used commands?

**Comment by cracker64** [comment]
Are you connecting to a specific server?
You don't have to type ANY server name to connect to the default one, just do '/connect'
Apparently there is a TPTMP server running on 'starcatcher.us' which is the incorrect master server location.
If you still feel like typing the address manually, it should be tptmp.starcatcher.us (this is a different server than the base starcatcher.us)

**Comment by handicraftsman** [comment]
Ohh, yes - no redirection xD

**Comment by handicraftsman** [comment]
Buuuttt... no online on sever!

**Comment by jacob1** [comment]
Try again later then, people aren't always online. At least you finally connected :)
